export const SIGNUP_ACTION = '[actions] signup user';
export const LOGIN_ACTION = '[actions] login user';
export const LOGOUT_ACTION = '[actions] logout user';
export const POST_MSG_ACTION = '[actions] post message';
export const SET_USER_TOKEN_DATA_MUTATION = '[mutations] set user token data';
export const GET_USER_TOKEN_GETTER = '[getters] auth user token';
export const IS_USER_AUTHENTICATE_GETTER = '[getters] is user authenticated';
export const PSEUDO_GETTER = '[getters] pseudo user';
export const ID_USER_GETTER = '[getters] id user';
